### ISSUE TITLE
样式有点怪怪的哈

### ISSUE THREAD

**Issue by luoxmc** [Mjhuu/vue-intro-step#1]
标题靠左对齐，内容又有个2rem的text-indent，内容不自动换行，按钮又不是居中的，这个样式看起来怪怪的哈，作者大大可以优化下么

**Comment by Mjhuu** [comment]
你可以给个设计图吗？作为理工男，实在不知道如何设计才好看，哈哈哈哈

**Comment by luoxmc** [comment]
还有个问题是在引导页滚动条依然可以滚动，下层的页面可以滑动

**Comment by luoxmc** [comment]
> 

插件现在的样式是这样的，图片地址 https://www.helloimg.com/image/ZPonGr
如果是bottom位置的话，文字就无法显示完整了，图片地址 https://www.helloimg.com/image/ZPobN1
我稍微调了下样式之后的效果是这样的 ，图片地址 https://www.helloimg.com/image/ZPoLbc

个人觉得居中会好一点哈，还有背景颜色透明度感觉可以稍微调浅一点，现在颜色有点深，小建议，哈哈。

**Comment by Mjhuu** [comment]
好的，下个版本，加一个自定义样式

**Comment by luoxmc** [comment]
按钮文字也能自定义就好了

**Comment by Mjhuu** [comment]
好的，上线后，告诉你

**Comment by Mjhuu** [comment]
上线啦，试一下吧

**Comment by luoxmc** [comment]
> 上线啦，试一下吧

厉害了，但是版本是1.0.9么，从npm安装的是1.0.9版本，但是好像没得啥变化哈，这些新加的参数设置了没效果

**Comment by Mjhuu** [comment]
<img width="282" alt="image" src="https://user-images.githubusercontent.com/45823607/170188381-5f201ec5-a4ec-4f8c-afd5-4645765de1c7.png">
1.0.11

**Comment by Mjhuu** [comment]
<img width="765" alt="image" src="https://user-images.githubusercontent.com/45823607/170188476-adcfa813-6e1e-4ab5-b117-a31ae5789566.png">
也增加了自定义插槽

**Comment by luoxmc** [comment]
可以了，非常完美，非常感谢，32个赞👍🏻。
之前下载不到最新版版的包原来是因为我把npm的源切成淘宝的源了，折腾半天哈哈哈

**Comment by Mjhuu** [comment]
譬如说一些需要提示的标签如果在页面上方，或者页面下方，个人建议：需要手动监听onNext或者onPrev去监听，先滚动到可视区域再去Promise resolve true来达到效果

**Comment by luoxmc** [comment]
> 譬如说一些需要提示的标签如果在页面上方，或者页面下方，个人建议：需要手动监听onNext或者onPrev去监听，先滚动到可视区域再去Promise resolve true来达到效果

好的，标题大小字体设置无效，因为样式表里面已经有一个加了 !important 的 font-size样式了，作者得空的时候可以修改下哈，要是再能禁用下层页面的滚动条就完美了。

**Comment by Mjhuu** [comment]
<img width="433" alt="image" src="https://user-images.githubusercontent.com/45823607/170192908-6988d104-2572-4136-9d33-5c6bc5787c1b.png">
<img width="314" alt="image" src="https://user-images.githubusercontent.com/45823607/170192916-f301f318-4ca9-4124-972b-5290bae6771b.png">
我可以呀，1.0.11

禁用下层页面的滚动条，你可以监听show变为true的时候，自己去禁止滚动，因为页面内部可能有很多元素，做不到每个都禁止，哪怕每个都禁止的话，性能就不好了，所以开发者可以自己控制是否禁止。

**Comment by Mjhuu** [comment]
<img width="429" alt="image" src="https://user-images.githubusercontent.com/45823607/170193267-3916f919-1b70-4aa0-90f3-2ce755123f3a.png">
如果是自己样式层级问题，可以这么传参

**Comment by luoxmc** [comment]
> <img alt="image" width="429" src="https://user-images.githubusercontent.com/45823607/170193267-3916f919-1b70-4aa0-90f3-2ce755123f3a.png">
> 
> 如果是自己样式层级问题，可以这么传参

多谢，确实是跟我用的vuetify框架的样式冲突了导致的
